# permissions for end users to view secretsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretsync-viewer-role
rules:
- apiGroups:
  - sync.spectro30
  resources:
  - secretsyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sync.spectro30
  resources:
  - secretsyncs/status
  verbs:
  - get
