apiVersion: sync.spectro30/v1
kind: SecretSync
metadata:
  name: sample-secret-sync
  namespace: demo
spec:
  sourceRef:
    name: md-ca
    namespace: demo
  targetNamespaces:
    - demox
    - demoy
